package UI;

import Datos.Tablero;
import Negocio.main;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmTablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    private boolean miTurno = true;
    private int numeroJugador = 0;
    private Tablero tablero = new Tablero();

    public frmTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPInfo = new javax.swing.JPanel();
        lblNombreJugador = new javax.swing.JLabel();
        lblfondoJugador = new javax.swing.JLabel();
        jPChat = new javax.swing.JPanel();
        tfChat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        jPTablero = new javax.swing.JPanel();
        btn02 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        lblTableroFondo = new javax.swing.JLabel();
        lblGato = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPInfo.setBackground(new java.awt.Color(51, 255, 255));
        jPInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreJugador.setText("Jugador:");
        jPInfo.add(lblNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 171, 34));
        jPInfo.add(lblfondoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 190, 510));

        jPanel1.add(jPInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 0, -1, 500));

        jPChat.setBackground(new java.awt.Color(204, 204, 255));

        taChat.setEditable(false);
        taChat.setColumns(20);
        taChat.setRows(5);
        jScrollPane1.setViewportView(taChat);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPChatLayout = new javax.swing.GroupLayout(jPChat);
        jPChat.setLayout(jPChatLayout);
        jPChatLayout.setHorizontalGroup(
            jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChatLayout.createSequentialGroup()
                .addComponent(tfChat, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPChatLayout.setVerticalGroup(
            jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPChatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)))
        );

        jPanel1.add(jPChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 610, 110));

        jPTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn02.setText("02");
        btn02.setContentAreaFilled(false);
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        jPTablero.add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 90));

        btn11.setText("11");
        btn11.setContentAreaFilled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPTablero.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 100));

        btn01.setText("01");
        btn01.setContentAreaFilled(false);
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        jPTablero.add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, 90));

        btn00.setText("00");
        btn00.setContentAreaFilled(false);
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        jPTablero.add(btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        btn10.setText("10");
        btn10.setContentAreaFilled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPTablero.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 100));

        btn12.setText("12");
        btn12.setContentAreaFilled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPTablero.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, 100));

        btn22.setText("22");
        btn22.setContentAreaFilled(false);
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPTablero.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, 90));

        btn21.setText("21");
        btn21.setContentAreaFilled(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPTablero.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 90));

        btn20.setText("20");
        btn20.setContentAreaFilled(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPTablero.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 90));

        lblTableroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mulimedia/IMG/Tablero.jpg"))); // NOI18N
        jPTablero.add(lblTableroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        jPanel1.add(jPTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 300));

        lblGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mulimedia/IMG/Gato.gif"))); // NOI18N
        jPanel1.add(lblGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 240, 390));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        AgregarFicha(1, 1);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        AgregarFicha(0, 2);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        AgregarFicha(0, 1);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        AgregarFicha(0, 0);
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        AgregarFicha(1, 0);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        AgregarFicha(1, 2);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        AgregarFicha(2, 0);
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        AgregarFicha(2, 1);
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        AgregarFicha(2, 2);
    }//GEN-LAST:event_btn22ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //tfChat
        String Envio = tfChat.getText();
        agregarMensaje(main.miControlador.getUsuario() + ": " + Envio);
        tfChat.setText("");
        main.miControlador.getMicliente().enviarMensaje(main.miControlador.getUsuario(), Envio);
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTablero().setVisible(true);
            }
        });
    }

    public void configurarJugador(int id, boolean Turno) {
        this.miTurno = Turno;
        this.numeroJugador = id;

    }

    public boolean isMiTurno() {
        return miTurno;
    }

    public void setMiTurno(boolean miTurno) {
        this.miTurno = miTurno;
    }

    public void cargar(String Nombre) {

        lblNombreJugador.setText(Nombre);

        ImageIcon imagen = new ImageIcon("src/Mulimedia/IMG/Fondo1.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(),
                lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        
        ImageIcon imagen2 = new ImageIcon("src/Mulimedia/IMG/fondo2.jpg");
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblfondoJugador.getWidth(),
                lblfondoJugador.getHeight(), Image.SCALE_DEFAULT));
        lblfondoJugador.setIcon(icono2);

        btn00.setText("");
        btn01.setText("");
        btn02.setText("");

        btn10.setText("");
        btn11.setText("");
        btn12.setText("");

        btn20.setText("");
        btn21.setText("");
        btn22.setText("");

        tablero.InicializarTablero();
    }

    public void AgregarFicha(int x, int y) {
        if (miTurno) {
            tablero.AgregarFicha(numeroJugador, x, y);
            miTurno = false;
            main.miControlador.getMicliente().enviarFicha(numeroJugador, x, y);
        }
        System.out.println(tablero.ImprimirTablero());
        ActualizarFichas();
    }

    public void AgregarFichaContrincante(int id, int x, int y) {

        tablero.AgregarFicha(id, x, y);
        miTurno = true;

        System.out.println(tablero.ImprimirTablero());
        ActualizarFichas();
    }

    public void ActualizarFichas() {
        int temp = 0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                temp = tablero.getMatriz()[i][j];
                String url = "";
                if (temp == 1) {
                    url = "src/Mulimedia/IMG/Face1.png";
                }
                if (temp == 2) {
                    url = "src/Mulimedia/IMG/face2.png";
                }
                if (i == 0 && j == 0 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn00.getWidth(),
                            btn00.getHeight(), Image.SCALE_DEFAULT));
                    btn00.setIcon(icono);
                }
                if (i == 0 && j == 1 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn01.getWidth(),
                            btn01.getHeight(), Image.SCALE_DEFAULT));
                    btn01.setIcon(icono);
                }
                if (i == 0 && j == 2 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn02.getWidth(),
                            btn02.getHeight(), Image.SCALE_DEFAULT));
                    btn02.setIcon(icono);
                }
                if (i == 1 && j == 0 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn10.getWidth(),
                            btn10.getHeight(), Image.SCALE_DEFAULT));
                    btn10.setIcon(icono);
                }
                if (i == 1 && j == 1 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn11.getWidth(),
                            btn11.getHeight(), Image.SCALE_DEFAULT));
                    btn11.setIcon(icono);
                }
                if (i == 1 && j == 2 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn12.getWidth(),
                            btn12.getHeight(), Image.SCALE_DEFAULT));
                    btn12.setIcon(icono);
                }
                if (i == 2 && j == 0 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn20.getWidth(),
                            btn20.getHeight(), Image.SCALE_DEFAULT));
                    btn20.setIcon(icono);
                }
                if (i == 2 && j == 1 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn21.getWidth(),
                            btn21.getHeight(), Image.SCALE_DEFAULT));
                    btn21.setIcon(icono);
                }
                if (i == 2 && j == 2 && temp != 0) {
                    ImageIcon imagen = new ImageIcon(url);
                    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btn22.getWidth(),
                            btn22.getHeight(), Image.SCALE_DEFAULT));
                    btn22.setIcon(icono);
                }

            }
        }

        if (tablero.Victoria()) {
            if (miTurno) {
                 JOptionPane.showMessageDialog(null, "Fin del Juego");
               
            } else {
                JOptionPane.showMessageDialog(null, "Ganador "
                        + "\n"
                        + "Jugador: "+lblNombreJugador.getText());
                      
            }
            /*
            frmTablero Ventana = new frmTablero();
            Ventana.cargar(lblNombreJugador.getText());
            Ventana.setVisible(true);
            this.dispose();*/
            main.miControlador.finDelJuego(this);
        }

    }

    public void agregarMensaje(String eMensaje) {
        taChat.setText(taChat.getText() + "\n" + eMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel jPChat;
    private javax.swing.JPanel jPInfo;
    private javax.swing.JPanel jPTablero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGato;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblTableroFondo;
    private javax.swing.JLabel lblfondoJugador;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfChat;
    // End of variables declaration//GEN-END:variables

}
