/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author SSDesth
 */
public class frmClienteLoading extends javax.swing.JFrame {

    /**
     * Creates new form frmLoading
     */
    public frmClienteLoading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/rojo.png"))); // NOI18N

        lblJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/rojo.png"))); // NOI18N

        lblJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/rojo.png"))); // NOI18N

        lblLoading.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 255));
        lblLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoading.setText("Esperando Jugadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(lblJugador1)
                .addGap(55, 55, 55)
                .addComponent(lblJugador2)
                .addGap(50, 50, 50)
                .addComponent(lblJugador3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJugador2)
                    .addComponent(lblJugador1)
                    .addComponent(lblJugador3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClienteLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClienteLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClienteLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClienteLoading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClienteLoading().setVisible(true);
            }
        });
    }

    /**
     * Carga la ventana junto con usu imajenes
     *
     * @param jugador
     */
    public void Cargador(int jugador) {
        ImageIcon imagen = new ImageIcon("src/Multimedia/loading.gif");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(),
                lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);

        switch (jugador) {
            case 1:
                CargadorJugador1();
                break;
            case 2:
                CargadorJugador2();
                break;
            case 3:
                CargadorJugador3();
                break;
        }

    }

    /**
     * carga el frm para 1 jugador
     */
    public void CargadorJugador1() {
        ImageIcon imagen = new ImageIcon("src/Multimedia/verde.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(40,
                40, Image.SCALE_DEFAULT));

        lblJugador1.setIcon(icono);
    }

    /**
     * carga el frm para 2 jugadores
     */
    public void CargadorJugador2() {
        ImageIcon imagen = new ImageIcon("src/Multimedia/verde.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(40,
                40, Image.SCALE_DEFAULT));

        lblJugador1.setIcon(icono);
        lblJugador2.setIcon(icono);
    }

    /**
     * carga el frm para 3 jugadores
     */
    public void CargadorJugador3() {
        ImageIcon imagen = new ImageIcon("src/Multimedia/verde.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(40,
                40, Image.SCALE_DEFAULT));

        lblJugador1.setIcon(icono);
        lblJugador2.setIcon(icono);
        lblJugador3.setIcon(icono);
    }

    /**
     * actualiza la cantidad de jugadores
     * @param numeroJugadores 
     */
    public void Actualizar(int numeroJugadores) {
        if (numeroJugadores == 2) {
            CargadorJugador2();
        } else {
            CargadorJugador3();
        }

    }

    public void ActualizarMensaje(String entrada) {
        lblLoading.setText(entrada);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables
}
